# Generated by Django 5.0.6 on 2024-05-15 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('current_price', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
