# Generated by Django 5.0.6 on 2024-05-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_alter_orderitem_product_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
