# Generated by Django 5.0.6 on 2024-06-04 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_checkoutinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutinfo',
            name='guest_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_shipping', to='store.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
