# Generated by Django 5.0.6 on 2024-06-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_checkoutinfo_guest_customer_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutinfo',
            name='guest_customer',
        ),
        migrations.AddField(
            model_name='checkoutinfo',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
